//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_Cinema.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Language", Namespace="http://schemas.datacontract.org/2004/07/Serveur_Cinema.Model")]
    [System.SerializableAttribute()]
    public partial class Language : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LanguageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client_Cinema.ServiceReference1.Film[] Language_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Last_UpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client_Cinema.ServiceReference1.Film[] Original_Language_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LanguageId {
            get {
                return this.LanguageIdField;
            }
            set {
                if ((this.LanguageIdField.Equals(value) != true)) {
                    this.LanguageIdField = value;
                    this.RaisePropertyChanged("LanguageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client_Cinema.ServiceReference1.Film[] Language_Id {
            get {
                return this.Language_IdField;
            }
            set {
                if ((object.ReferenceEquals(this.Language_IdField, value) != true)) {
                    this.Language_IdField = value;
                    this.RaisePropertyChanged("Language_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Last_Update {
            get {
                return this.Last_UpdateField;
            }
            set {
                if ((this.Last_UpdateField.Equals(value) != true)) {
                    this.Last_UpdateField = value;
                    this.RaisePropertyChanged("Last_Update");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client_Cinema.ServiceReference1.Film[] Original_Language_Id {
            get {
                return this.Original_Language_IdField;
            }
            set {
                if ((object.ReferenceEquals(this.Original_Language_IdField, value) != true)) {
                    this.Original_Language_IdField = value;
                    this.RaisePropertyChanged("Original_Language_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Film", Namespace="http://schemas.datacontract.org/2004/07/Serveur_Cinema.Model")]
    [System.SerializableAttribute()]
    public partial class Film : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FilmIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client_Cinema.ServiceReference1.Film_Actor[] Film_ActorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client_Cinema.ServiceReference1.Film_Category[] Film_CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client_Cinema.ServiceReference1.Inventory[] InventoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Last_UpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Release_YearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Rental_DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Rental_RateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Replacement_CostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Special_FeaturesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FilmId {
            get {
                return this.FilmIdField;
            }
            set {
                if ((this.FilmIdField.Equals(value) != true)) {
                    this.FilmIdField = value;
                    this.RaisePropertyChanged("FilmId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client_Cinema.ServiceReference1.Film_Actor[] Film_ActorId {
            get {
                return this.Film_ActorIdField;
            }
            set {
                if ((object.ReferenceEquals(this.Film_ActorIdField, value) != true)) {
                    this.Film_ActorIdField = value;
                    this.RaisePropertyChanged("Film_ActorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client_Cinema.ServiceReference1.Film_Category[] Film_CategoryId {
            get {
                return this.Film_CategoryIdField;
            }
            set {
                if ((object.ReferenceEquals(this.Film_CategoryIdField, value) != true)) {
                    this.Film_CategoryIdField = value;
                    this.RaisePropertyChanged("Film_CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client_Cinema.ServiceReference1.Inventory[] InventoryId {
            get {
                return this.InventoryIdField;
            }
            set {
                if ((object.ReferenceEquals(this.InventoryIdField, value) != true)) {
                    this.InventoryIdField = value;
                    this.RaisePropertyChanged("InventoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Last_Update {
            get {
                return this.Last_UpdateField;
            }
            set {
                if ((this.Last_UpdateField.Equals(value) != true)) {
                    this.Last_UpdateField = value;
                    this.RaisePropertyChanged("Last_Update");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Length {
            get {
                return this.LengthField;
            }
            set {
                if ((this.LengthField.Equals(value) != true)) {
                    this.LengthField = value;
                    this.RaisePropertyChanged("Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((object.ReferenceEquals(this.RatingField, value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Release_Year {
            get {
                return this.Release_YearField;
            }
            set {
                if ((object.ReferenceEquals(this.Release_YearField, value) != true)) {
                    this.Release_YearField = value;
                    this.RaisePropertyChanged("Release_Year");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rental_Duration {
            get {
                return this.Rental_DurationField;
            }
            set {
                if ((this.Rental_DurationField.Equals(value) != true)) {
                    this.Rental_DurationField = value;
                    this.RaisePropertyChanged("Rental_Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rental_Rate {
            get {
                return this.Rental_RateField;
            }
            set {
                if ((this.Rental_RateField.Equals(value) != true)) {
                    this.Rental_RateField = value;
                    this.RaisePropertyChanged("Rental_Rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Replacement_Cost {
            get {
                return this.Replacement_CostField;
            }
            set {
                if ((this.Replacement_CostField.Equals(value) != true)) {
                    this.Replacement_CostField = value;
                    this.RaisePropertyChanged("Replacement_Cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Special_Features {
            get {
                return this.Special_FeaturesField;
            }
            set {
                if ((object.ReferenceEquals(this.Special_FeaturesField, value) != true)) {
                    this.Special_FeaturesField = value;
                    this.RaisePropertyChanged("Special_Features");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Film_Actor", Namespace="http://schemas.datacontract.org/2004/07/Serveur_Cinema.Model")]
    [System.SerializableAttribute()]
    public partial class Film_Actor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ActorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FilmIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Film_ActorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Last_UpdateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActorId {
            get {
                return this.ActorIdField;
            }
            set {
                if ((this.ActorIdField.Equals(value) != true)) {
                    this.ActorIdField = value;
                    this.RaisePropertyChanged("ActorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FilmId {
            get {
                return this.FilmIdField;
            }
            set {
                if ((this.FilmIdField.Equals(value) != true)) {
                    this.FilmIdField = value;
                    this.RaisePropertyChanged("FilmId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Film_ActorId {
            get {
                return this.Film_ActorIdField;
            }
            set {
                if ((this.Film_ActorIdField.Equals(value) != true)) {
                    this.Film_ActorIdField = value;
                    this.RaisePropertyChanged("Film_ActorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Last_Update {
            get {
                return this.Last_UpdateField;
            }
            set {
                if ((this.Last_UpdateField.Equals(value) != true)) {
                    this.Last_UpdateField = value;
                    this.RaisePropertyChanged("Last_Update");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Film_Category", Namespace="http://schemas.datacontract.org/2004/07/Serveur_Cinema.Model")]
    [System.SerializableAttribute()]
    public partial class Film_Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FilmIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Film_CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Last_UpdateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FilmId {
            get {
                return this.FilmIdField;
            }
            set {
                if ((this.FilmIdField.Equals(value) != true)) {
                    this.FilmIdField = value;
                    this.RaisePropertyChanged("FilmId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Film_CategoryId {
            get {
                return this.Film_CategoryIdField;
            }
            set {
                if ((this.Film_CategoryIdField.Equals(value) != true)) {
                    this.Film_CategoryIdField = value;
                    this.RaisePropertyChanged("Film_CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Last_Update {
            get {
                return this.Last_UpdateField;
            }
            set {
                if ((this.Last_UpdateField.Equals(value) != true)) {
                    this.Last_UpdateField = value;
                    this.RaisePropertyChanged("Last_Update");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Inventory", Namespace="http://schemas.datacontract.org/2004/07/Serveur_Cinema.Model")]
    [System.SerializableAttribute()]
    public partial class Inventory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InventoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Last_updateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client_Cinema.ServiceReference1.Rental[] RentalIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InventoryId {
            get {
                return this.InventoryIdField;
            }
            set {
                if ((this.InventoryIdField.Equals(value) != true)) {
                    this.InventoryIdField = value;
                    this.RaisePropertyChanged("InventoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Last_update {
            get {
                return this.Last_updateField;
            }
            set {
                if ((this.Last_updateField.Equals(value) != true)) {
                    this.Last_updateField = value;
                    this.RaisePropertyChanged("Last_update");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client_Cinema.ServiceReference1.Rental[] RentalId {
            get {
                return this.RentalIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RentalIdField, value) != true)) {
                    this.RentalIdField = value;
                    this.RaisePropertyChanged("RentalId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rental", Namespace="http://schemas.datacontract.org/2004/07/Serveur_Cinema.Model")]
    [System.SerializableAttribute()]
    public partial class Rental : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Last_UpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client_Cinema.ServiceReference1.Payement[] PayementIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RentalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Rental_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Return_DateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Last_Update {
            get {
                return this.Last_UpdateField;
            }
            set {
                if ((this.Last_UpdateField.Equals(value) != true)) {
                    this.Last_UpdateField = value;
                    this.RaisePropertyChanged("Last_Update");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client_Cinema.ServiceReference1.Payement[] PayementId {
            get {
                return this.PayementIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PayementIdField, value) != true)) {
                    this.PayementIdField = value;
                    this.RaisePropertyChanged("PayementId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RentalId {
            get {
                return this.RentalIdField;
            }
            set {
                if ((this.RentalIdField.Equals(value) != true)) {
                    this.RentalIdField = value;
                    this.RaisePropertyChanged("RentalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Rental_Date {
            get {
                return this.Rental_DateField;
            }
            set {
                if ((this.Rental_DateField.Equals(value) != true)) {
                    this.Rental_DateField = value;
                    this.RaisePropertyChanged("Rental_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Return_Date {
            get {
                return this.Return_DateField;
            }
            set {
                if ((this.Return_DateField.Equals(value) != true)) {
                    this.Return_DateField = value;
                    this.RaisePropertyChanged("Return_Date");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Payement", Namespace="http://schemas.datacontract.org/2004/07/Serveur_Cinema.Model")]
    [System.SerializableAttribute()]
    public partial class Payement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Last_UpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PayementIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Payement_DateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Last_Update {
            get {
                return this.Last_UpdateField;
            }
            set {
                if ((this.Last_UpdateField.Equals(value) != true)) {
                    this.Last_UpdateField = value;
                    this.RaisePropertyChanged("Last_Update");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PayementId {
            get {
                return this.PayementIdField;
            }
            set {
                if ((this.PayementIdField.Equals(value) != true)) {
                    this.PayementIdField = value;
                    this.RaisePropertyChanged("PayementId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Payement_Date {
            get {
                return this.Payement_DateField;
            }
            set {
                if ((this.Payement_DateField.Equals(value) != true)) {
                    this.Payement_DateField = value;
                    this.RaisePropertyChanged("Payement_Date");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Actor", Namespace="http://schemas.datacontract.org/2004/07/Serveur_Cinema.Model")]
    [System.SerializableAttribute()]
    public partial class Actor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ActorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client_Cinema.ServiceReference1.Film_Actor[] Film_ActorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string First_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Last_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Last_UpdateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActorId {
            get {
                return this.ActorIdField;
            }
            set {
                if ((this.ActorIdField.Equals(value) != true)) {
                    this.ActorIdField = value;
                    this.RaisePropertyChanged("ActorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client_Cinema.ServiceReference1.Film_Actor[] Film_ActorId {
            get {
                return this.Film_ActorIdField;
            }
            set {
                if ((object.ReferenceEquals(this.Film_ActorIdField, value) != true)) {
                    this.Film_ActorIdField = value;
                    this.RaisePropertyChanged("Film_ActorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string First_Name {
            get {
                return this.First_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.First_NameField, value) != true)) {
                    this.First_NameField = value;
                    this.RaisePropertyChanged("First_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Last_Name {
            get {
                return this.Last_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Last_NameField, value) != true)) {
                    this.Last_NameField = value;
                    this.RaisePropertyChanged("Last_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Last_Update {
            get {
                return this.Last_UpdateField;
            }
            set {
                if ((this.Last_UpdateField.Equals(value) != true)) {
                    this.Last_UpdateField = value;
                    this.RaisePropertyChanged("Last_Update");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Store", Namespace="http://schemas.datacontract.org/2004/07/Serveur_Cinema.Model")]
    [System.SerializableAttribute()]
    public partial class Store : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client_Cinema.ServiceReference1.Customer[] CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client_Cinema.ServiceReference1.Inventory[] InventoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Last_updateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client_Cinema.ServiceReference1.Staff[] StaffIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StoreIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client_Cinema.ServiceReference1.Customer[] CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerIdField, value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client_Cinema.ServiceReference1.Inventory[] InventoryId {
            get {
                return this.InventoryIdField;
            }
            set {
                if ((object.ReferenceEquals(this.InventoryIdField, value) != true)) {
                    this.InventoryIdField = value;
                    this.RaisePropertyChanged("InventoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Last_update {
            get {
                return this.Last_updateField;
            }
            set {
                if ((this.Last_updateField.Equals(value) != true)) {
                    this.Last_updateField = value;
                    this.RaisePropertyChanged("Last_update");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client_Cinema.ServiceReference1.Staff[] StaffId {
            get {
                return this.StaffIdField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffIdField, value) != true)) {
                    this.StaffIdField = value;
                    this.RaisePropertyChanged("StaffId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StoreId {
            get {
                return this.StoreIdField;
            }
            set {
                if ((this.StoreIdField.Equals(value) != true)) {
                    this.StoreIdField = value;
                    this.RaisePropertyChanged("StoreId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/Serveur_Cinema.Model")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Create_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string First_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Last_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Last_UpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client_Cinema.ServiceReference1.Payement[] PayementIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client_Cinema.ServiceReference1.Rental[] RentalIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((object.ReferenceEquals(this.ActiveField, value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Create_Date {
            get {
                return this.Create_DateField;
            }
            set {
                if ((this.Create_DateField.Equals(value) != true)) {
                    this.Create_DateField = value;
                    this.RaisePropertyChanged("Create_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string First_Name {
            get {
                return this.First_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.First_NameField, value) != true)) {
                    this.First_NameField = value;
                    this.RaisePropertyChanged("First_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Last_Name {
            get {
                return this.Last_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Last_NameField, value) != true)) {
                    this.Last_NameField = value;
                    this.RaisePropertyChanged("Last_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Last_Update {
            get {
                return this.Last_UpdateField;
            }
            set {
                if ((this.Last_UpdateField.Equals(value) != true)) {
                    this.Last_UpdateField = value;
                    this.RaisePropertyChanged("Last_Update");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client_Cinema.ServiceReference1.Payement[] PayementId {
            get {
                return this.PayementIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PayementIdField, value) != true)) {
                    this.PayementIdField = value;
                    this.RaisePropertyChanged("PayementId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client_Cinema.ServiceReference1.Rental[] RentalId {
            get {
                return this.RentalIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RentalIdField, value) != true)) {
                    this.RentalIdField = value;
                    this.RaisePropertyChanged("RentalId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Staff", Namespace="http://schemas.datacontract.org/2004/07/Serveur_Cinema.Model")]
    [System.SerializableAttribute()]
    public partial class Staff : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string First_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Last_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Last_UpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client_Cinema.ServiceReference1.Payement[] PayementIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client_Cinema.ServiceReference1.Rental[] RentalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StaffIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client_Cinema.ServiceReference1.Store[] StoreIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string First_Name {
            get {
                return this.First_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.First_NameField, value) != true)) {
                    this.First_NameField = value;
                    this.RaisePropertyChanged("First_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Last_Name {
            get {
                return this.Last_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Last_NameField, value) != true)) {
                    this.Last_NameField = value;
                    this.RaisePropertyChanged("Last_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Last_Update {
            get {
                return this.Last_UpdateField;
            }
            set {
                if ((this.Last_UpdateField.Equals(value) != true)) {
                    this.Last_UpdateField = value;
                    this.RaisePropertyChanged("Last_Update");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client_Cinema.ServiceReference1.Payement[] PayementId {
            get {
                return this.PayementIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PayementIdField, value) != true)) {
                    this.PayementIdField = value;
                    this.RaisePropertyChanged("PayementId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client_Cinema.ServiceReference1.Rental[] RentalId {
            get {
                return this.RentalIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RentalIdField, value) != true)) {
                    this.RentalIdField = value;
                    this.RaisePropertyChanged("RentalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StaffId {
            get {
                return this.StaffIdField;
            }
            set {
                if ((this.StaffIdField.Equals(value) != true)) {
                    this.StaffIdField = value;
                    this.RaisePropertyChanged("StaffId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client_Cinema.ServiceReference1.Store[] StoreId {
            get {
                return this.StoreIdField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreIdField, value) != true)) {
                    this.StoreIdField = value;
                    this.RaisePropertyChanged("StoreId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/Serveur_Cinema.Model")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AddressIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Adresse_Name1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Adresse_Name2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client_Cinema.ServiceReference1.Customer[] CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistrictField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Last_UpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Postal_CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client_Cinema.ServiceReference1.Staff[] StaffIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client_Cinema.ServiceReference1.Store[] StoreIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AddressId {
            get {
                return this.AddressIdField;
            }
            set {
                if ((this.AddressIdField.Equals(value) != true)) {
                    this.AddressIdField = value;
                    this.RaisePropertyChanged("AddressId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adresse_Name1 {
            get {
                return this.Adresse_Name1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Adresse_Name1Field, value) != true)) {
                    this.Adresse_Name1Field = value;
                    this.RaisePropertyChanged("Adresse_Name1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adresse_Name2 {
            get {
                return this.Adresse_Name2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Adresse_Name2Field, value) != true)) {
                    this.Adresse_Name2Field = value;
                    this.RaisePropertyChanged("Adresse_Name2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client_Cinema.ServiceReference1.Customer[] CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerIdField, value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string District {
            get {
                return this.DistrictField;
            }
            set {
                if ((object.ReferenceEquals(this.DistrictField, value) != true)) {
                    this.DistrictField = value;
                    this.RaisePropertyChanged("District");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Last_Update {
            get {
                return this.Last_UpdateField;
            }
            set {
                if ((this.Last_UpdateField.Equals(value) != true)) {
                    this.Last_UpdateField = value;
                    this.RaisePropertyChanged("Last_Update");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Postal_Code {
            get {
                return this.Postal_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Postal_CodeField, value) != true)) {
                    this.Postal_CodeField = value;
                    this.RaisePropertyChanged("Postal_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client_Cinema.ServiceReference1.Staff[] StaffId {
            get {
                return this.StaffIdField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffIdField, value) != true)) {
                    this.StaffIdField = value;
                    this.RaisePropertyChanged("StaffId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client_Cinema.ServiceReference1.Store[] StoreId {
            get {
                return this.StoreIdField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreIdField, value) != true)) {
                    this.StoreIdField = value;
                    this.RaisePropertyChanged("StoreId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ILanguageService")]
    public interface ILanguageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILanguageService/Addlangage", ReplyAction="http://tempuri.org/ILanguageService/AddlangageResponse")]
        Client_Cinema.ServiceReference1.Language Addlangage(Client_Cinema.ServiceReference1.Language Langue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILanguageService/Addlangage", ReplyAction="http://tempuri.org/ILanguageService/AddlangageResponse")]
        System.Threading.Tasks.Task<Client_Cinema.ServiceReference1.Language> AddlangageAsync(Client_Cinema.ServiceReference1.Language Langue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILanguageService/Addactor", ReplyAction="http://tempuri.org/ILanguageService/AddactorResponse")]
        Client_Cinema.ServiceReference1.Actor Addactor(Client_Cinema.ServiceReference1.Actor Act);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILanguageService/Addactor", ReplyAction="http://tempuri.org/ILanguageService/AddactorResponse")]
        System.Threading.Tasks.Task<Client_Cinema.ServiceReference1.Actor> AddactorAsync(Client_Cinema.ServiceReference1.Actor Act);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILanguageService/Addstore", ReplyAction="http://tempuri.org/ILanguageService/AddstoreResponse")]
        Client_Cinema.ServiceReference1.Store Addstore(Client_Cinema.ServiceReference1.Store str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILanguageService/Addstore", ReplyAction="http://tempuri.org/ILanguageService/AddstoreResponse")]
        System.Threading.Tasks.Task<Client_Cinema.ServiceReference1.Store> AddstoreAsync(Client_Cinema.ServiceReference1.Store str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILanguageService/Addadresse", ReplyAction="http://tempuri.org/ILanguageService/AddadresseResponse")]
        Client_Cinema.ServiceReference1.Address Addadresse(Client_Cinema.ServiceReference1.Address ad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILanguageService/Addadresse", ReplyAction="http://tempuri.org/ILanguageService/AddadresseResponse")]
        System.Threading.Tasks.Task<Client_Cinema.ServiceReference1.Address> AddadresseAsync(Client_Cinema.ServiceReference1.Address ad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILanguageService/Addfilm", ReplyAction="http://tempuri.org/ILanguageService/AddfilmResponse")]
        Client_Cinema.ServiceReference1.Film Addfilm(Client_Cinema.ServiceReference1.Film fl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILanguageService/Addfilm", ReplyAction="http://tempuri.org/ILanguageService/AddfilmResponse")]
        System.Threading.Tasks.Task<Client_Cinema.ServiceReference1.Film> AddfilmAsync(Client_Cinema.ServiceReference1.Film fl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILanguageService/AddStaff", ReplyAction="http://tempuri.org/ILanguageService/AddStaffResponse")]
        Client_Cinema.ServiceReference1.Staff AddStaff(Client_Cinema.ServiceReference1.Staff staf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILanguageService/AddStaff", ReplyAction="http://tempuri.org/ILanguageService/AddStaffResponse")]
        System.Threading.Tasks.Task<Client_Cinema.ServiceReference1.Staff> AddStaffAsync(Client_Cinema.ServiceReference1.Staff staf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILanguageService/AddCustomer", ReplyAction="http://tempuri.org/ILanguageService/AddCustomerResponse")]
        Client_Cinema.ServiceReference1.Customer AddCustomer(Client_Cinema.ServiceReference1.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILanguageService/AddCustomer", ReplyAction="http://tempuri.org/ILanguageService/AddCustomerResponse")]
        System.Threading.Tasks.Task<Client_Cinema.ServiceReference1.Customer> AddCustomerAsync(Client_Cinema.ServiceReference1.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILanguageService/Listestore", ReplyAction="http://tempuri.org/ILanguageService/ListestoreResponse")]
        Client_Cinema.ServiceReference1.Store[] Listestore();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILanguageService/Listestore", ReplyAction="http://tempuri.org/ILanguageService/ListestoreResponse")]
        System.Threading.Tasks.Task<Client_Cinema.ServiceReference1.Store[]> ListestoreAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILanguageServiceChannel : Client_Cinema.ServiceReference1.ILanguageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LanguageServiceClient : System.ServiceModel.ClientBase<Client_Cinema.ServiceReference1.ILanguageService>, Client_Cinema.ServiceReference1.ILanguageService {
        
        public LanguageServiceClient() {
        }
        
        public LanguageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LanguageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LanguageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LanguageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client_Cinema.ServiceReference1.Language Addlangage(Client_Cinema.ServiceReference1.Language Langue) {
            return base.Channel.Addlangage(Langue);
        }
        
        public System.Threading.Tasks.Task<Client_Cinema.ServiceReference1.Language> AddlangageAsync(Client_Cinema.ServiceReference1.Language Langue) {
            return base.Channel.AddlangageAsync(Langue);
        }
        
        public Client_Cinema.ServiceReference1.Actor Addactor(Client_Cinema.ServiceReference1.Actor Act) {
            return base.Channel.Addactor(Act);
        }
        
        public System.Threading.Tasks.Task<Client_Cinema.ServiceReference1.Actor> AddactorAsync(Client_Cinema.ServiceReference1.Actor Act) {
            return base.Channel.AddactorAsync(Act);
        }
        
        public Client_Cinema.ServiceReference1.Store Addstore(Client_Cinema.ServiceReference1.Store str) {
            return base.Channel.Addstore(str);
        }
        
        public System.Threading.Tasks.Task<Client_Cinema.ServiceReference1.Store> AddstoreAsync(Client_Cinema.ServiceReference1.Store str) {
            return base.Channel.AddstoreAsync(str);
        }
        
        public Client_Cinema.ServiceReference1.Address Addadresse(Client_Cinema.ServiceReference1.Address ad) {
            return base.Channel.Addadresse(ad);
        }
        
        public System.Threading.Tasks.Task<Client_Cinema.ServiceReference1.Address> AddadresseAsync(Client_Cinema.ServiceReference1.Address ad) {
            return base.Channel.AddadresseAsync(ad);
        }
        
        public Client_Cinema.ServiceReference1.Film Addfilm(Client_Cinema.ServiceReference1.Film fl) {
            return base.Channel.Addfilm(fl);
        }
        
        public System.Threading.Tasks.Task<Client_Cinema.ServiceReference1.Film> AddfilmAsync(Client_Cinema.ServiceReference1.Film fl) {
            return base.Channel.AddfilmAsync(fl);
        }
        
        public Client_Cinema.ServiceReference1.Staff AddStaff(Client_Cinema.ServiceReference1.Staff staf) {
            return base.Channel.AddStaff(staf);
        }
        
        public System.Threading.Tasks.Task<Client_Cinema.ServiceReference1.Staff> AddStaffAsync(Client_Cinema.ServiceReference1.Staff staf) {
            return base.Channel.AddStaffAsync(staf);
        }
        
        public Client_Cinema.ServiceReference1.Customer AddCustomer(Client_Cinema.ServiceReference1.Customer customer) {
            return base.Channel.AddCustomer(customer);
        }
        
        public System.Threading.Tasks.Task<Client_Cinema.ServiceReference1.Customer> AddCustomerAsync(Client_Cinema.ServiceReference1.Customer customer) {
            return base.Channel.AddCustomerAsync(customer);
        }
        
        public Client_Cinema.ServiceReference1.Store[] Listestore() {
            return base.Channel.Listestore();
        }
        
        public System.Threading.Tasks.Task<Client_Cinema.ServiceReference1.Store[]> ListestoreAsync() {
            return base.Channel.ListestoreAsync();
        }
    }
}
